# Generated by Django 6.0.6 on 2026-07-01 17:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLedger',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_ref', models.CharField(db_index=True, help_text='Gateway transaction ID; unique for idempotency', max_length=200, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('captured', 'Captured'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('gateway', models.CharField(default='razorpay', max_length=50)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('receipt_uri', models.URLField(blank=True, help_text='MinIO URI of generated receipt PDF')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='admissions.enrollment')),
                ('sub_center', models.ForeignKey(help_text='Owning sub-center (tenant). Filtered by TenantManager.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='partners.subcenter')),
            ],
            options={
                'db_table': 'payment_ledgers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['enrollment', 'status'], name='payment_led_enrollm_a49f37_idx'), models.Index(fields=['sub_center', 'status'], name='payment_led_sub_cen_fb4c84_idx'), models.Index(fields=['-created_at'], name='payment_led_created_63f256_idx')],
            },
        ),
    ]
