# Generated by Django 5.2.15 on 2026-07-02 00:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_student_course_student_lead_owner_and_more'),
        ('aggregator', '0002_course_eligibility_criteria_json'),
        ('finance', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FLAT', 'Flat Fee')], default='PERCENTAGE', max_length=20)),
                ('rule_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='aggregator.course')),
            ],
            options={
                'db_table': 'commission_rules',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], db_index=True, default='Unpaid', max_length=20)),
                ('students', models.ManyToManyField(related_name='invoices', to='admissions.student')),
                ('sub_center', models.ForeignKey(help_text='Owning sub-center (tenant). Filtered by TenantManager.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='partners.subcenter')),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway_reference', models.CharField(db_index=True, max_length=200, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Pending', 'Pending')], db_index=True, default='Pending', max_length=20)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.invoice')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='UniversityPayoutLedger',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rimit_commission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payable_to_university', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_ledgers', to='admissions.student')),
                ('sub_center', models.ForeignKey(help_text='Owning sub-center (tenant). Filtered by TenantManager.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='partners.subcenter')),
            ],
            options={
                'db_table': 'university_payout_ledgers',
            },
        ),
    ]
