# Generated by Django 5.2.15 on 2026-07-02 11:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_add_dpdp_consent'),
        ('finance', '0002_commissionrule_invoice_transaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='students',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], db_index=True, default='Unpaid', max_length=20),
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_fee', models.DecimalField(decimal_places=2, help_text='Locked course fee at time of checkout', max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='finance.invoice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_line_items', to='admissions.student')),
            ],
            options={
                'db_table': 'invoice_line_items',
            },
        ),
    ]
