# Generated by Django 5.2.15 on 2026-07-13 21:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0006_rename_university_d_course_i_0d9f50_idx_university__course__3100d4_idx'),
        ('finance', '0005_university_payout_ledger_breakdown'),
        ('partners', '0004_rename_sub_center__sub_cen_68c6ab_idx_sub_center__sub_cen_e122f0_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universitypayoutledger',
            old_name='gross_pool',
            new_name='payable_to_univ',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='universitypayoutledger',
            name='cleared_at',
        ),
        migrations.RemoveField(
            model_name='universitypayoutledger',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='universitypayoutledger',
            name='net_payable',
        ),
        migrations.RemoveField(
            model_name='universitypayoutledger',
            name='payable_to_university',
        ),
        migrations.RemoveField(
            model_name='universitypayoutledger',
            name='student',
        ),
        migrations.RemoveField(
            model_name='universitypayoutledger',
            name='sub_center_commission',
        ),
        migrations.RemoveField(
            model_name='universitypayoutledger',
            name='total_fee',
        ),
        migrations.RemoveField(
            model_name='universitypayoutledger',
            name='university_share',
        ),
        migrations.AddField(
            model_name='invoice',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='net_payable_collected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sub_center_commission_deducted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='universitypayoutledger',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='universitypayoutledger',
            name='total_collected',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Reflects Net Payable from checkout', max_digits=12),
        ),
        migrations.AddField(
            model_name='universitypayoutledger',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payout_ledgers', to='aggregator.university'),
        ),
        migrations.AlterField(
            model_name='universitypayoutledger',
            name='rimit_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='SubCenterCommission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commission_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_center_commissions', to='aggregator.course')),
                ('sub_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='partners.subcenter')),
            ],
            options={
                'db_table': 'sub_center_commissions',
                'unique_together': {('sub_center', 'course')},
            },
        ),
        migrations.DeleteModel(
            name='CommissionRule',
        ),
    ]
