# Generated by Django 5.2.16 on 2026-07-29 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_add_enrollment_admission_fields'),
        ('finance', '0006_rename_gross_pool_universitypayoutledger_payable_to_univ_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_line_items', to='admissions.enrollment'),
        ),
    ]
