# Generated by Django 5.2.16 on 2026-08-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_invoicelineitem_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentledger',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentledger',
            name='screenshot_uri',
            field=models.URLField(blank=True, help_text='MinIO/S3 URI of the uploaded payment screenshot'),
        ),
    ]
