# Generated by Django 6.0.6 on 2026-07-01 17:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadIngestionLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('meta', 'Meta Ads (FB/Instagram)'), ('google', 'Google Ads'), ('referral', 'Referral')], db_index=True, max_length=30)),
                ('leadgen_id', models.CharField(db_index=True, help_text='Source-system lead ID for dedup', max_length=200, unique=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('normalized_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('ingested', 'Ingested'), ('fetch_failed', 'Fetch Failed'), ('dead_letter', 'Dead Letter'), ('converted', 'Converted to Student')], db_index=True, default='ingested', max_length=30)),
                ('error_msg', models.TextField(blank=True)),
                ('campaign_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('assigned_sub_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to='partners.subcenter')),
                ('converted_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_leads', to='admissions.student')),
            ],
            options={
                'db_table': 'lead_ingestion_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', 'status'], name='lead_ingest_source_6dc246_idx'), models.Index(fields=['campaign_id'], name='lead_ingest_campaig_5e6160_idx'), models.Index(fields=['-created_at'], name='lead_ingest_created_a4b3a6_idx')],
            },
        ),
    ]
