# Generated by Django 6.0.6 on 2026-07-01 17:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient', models.CharField(db_index=True, max_length=200)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email')], db_index=True, max_length=20)),
                ('template_id', models.CharField(db_index=True, max_length=100)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('message_body', models.TextField(blank=True)),
                ('delivery_status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered')], db_index=True, default='queued', max_length=20)),
                ('external_message_id', models.CharField(blank=True, db_index=True, help_text='WhatsApp message_id / SES message_id for idempotency', max_length=200)),
                ('error_msg', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('related_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='admissions.enrollment')),
            ],
            options={
                'db_table': 'notification_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel', 'delivery_status'], name='notificatio_channel_a7c7f8_idx'), models.Index(fields=['template_id'], name='notificatio_templat_a4bc3e_idx'), models.Index(fields=['-created_at'], name='notificatio_created_f8e81a_idx')],
            },
        ),
    ]
