FROM oven/bun:1 AS base
WORKDIR /app
COPY package.json bun.lock* package-lock.json* ./
RUN bun install
COPY . .
RUN bun run db:generate || true

ENV NODE_ENV=production
ENV API_URL="http://app:8000"
ENV NEXT_PUBLIC_API_URL="http://app:8000"
ENV HOSTNAME="0.0.0.0"
ENV PORT=80

# Run production build
RUN bun run build

# Start in production mode
CMD ["bun", "run", "start"]
