# Generated by Django 6.0.6 on 2026-07-01 17:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aggregator', '0001_initial'),
        ('partners', '0001_initial'),
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_index=True, max_length=300)),
                ('dob', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('primary_phone', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('aadhar_hash', models.CharField(db_index=True, help_text='SHA-256 hash of salted Aadhar number', max_length=64, unique=True)),
                ('address_data', models.JSONField(blank=True, default=dict)),
                ('parent_name', models.CharField(blank=True, max_length=300)),
                ('parent_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sub_center', models.ForeignKey(help_text='Owning sub-center (tenant). Filtered by TenantManager.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='partners.subcenter')),
            ],
            options={
                'db_table': 'students',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Document Verified', 'Document Verified'), ('Fee Pending', 'Fee Pending'), ('Fee Paid', 'Fee Paid'), ('Enrolled', 'Enrolled'), ('Enrollment Generated', 'Enrollment Generated'), ('Cancelled', 'Cancelled')], db_index=True, default='Applied', max_length=30)),
                ('enrollment_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('rejected_reason', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='aggregator.course')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='rules.intakesession')),
                ('sub_center', models.ForeignKey(help_text='Owning sub-center (tenant). Filtered by TenantManager.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='partners.subcenter')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='admissions.student')),
            ],
            options={
                'db_table': 'enrollments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAcademicHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qualification', models.CharField(choices=[('10th', '10th Standard'), ('12th', '12th Standard'), ('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('Diploma', 'Diploma')], db_index=True, max_length=20)),
                ('institution', models.CharField(max_length=300)),
                ('board_university', models.CharField(max_length=300)),
                ('year_of_passing', models.PositiveIntegerField()),
                ('score_type', models.CharField(choices=[('percentage', 'Percentage'), ('cgpa', 'CGPA'), ('grade', 'Grade')], max_length=20)),
                ('score_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('subject_stream', models.CharField(blank=True, max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_histories', to='admissions.student')),
            ],
            options={
                'db_table': 'student_academic_histories',
                'ordering': ['-year_of_passing'],
            },
        ),
        migrations.CreateModel(
            name='StudentDoc',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_category', models.CharField(choices=[('identity', 'Identity Proof'), ('marklist', 'Marklist / Certificate'), ('migration', 'Migration Certificate'), ('experience', 'Experience Certificate'), ('photo', 'Passport Photo'), ('other', 'Other')], db_index=True, max_length=30)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('s3_object_uri', models.TextField()),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('academic_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='admissions.studentacademichistory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.student')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_student_docs', to='partners.systemuser')),
            ],
            options={
                'db_table': 'student_docs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['sub_center', 'is_active'], name='students_sub_cen_6a9ea8_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['primary_phone'], name='students_primary_8f9d06_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['full_name'], name='students_full_na_365b2b_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['sub_center', 'status'], name='enrollments_sub_cen_b38543_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['session', 'status'], name='enrollments_session_f33d00_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'course', 'session'], name='enrollments_student_6eede6_idx'),
        ),
        migrations.AddIndex(
            model_name='studentacademichistory',
            index=models.Index(fields=['student', 'qualification'], name='student_aca_student_62ccf8_idx'),
        ),
        migrations.AddIndex(
            model_name='studentdoc',
            index=models.Index(fields=['student', 'doc_category'], name='student_doc_student_09adeb_idx'),
        ),
        migrations.AddIndex(
            model_name='studentdoc',
            index=models.Index(fields=['status'], name='student_doc_status_0ce65b_idx'),
        ),
    ]
