# Generated by Django 5.2.15 on 2026-07-02 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
        ('aggregator', '0002_course_eligibility_criteria_json'),
        ('rules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_leads', to='aggregator.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='lead_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='lead_status',
            field=models.CharField(choices=[('Pending Payment', 'Pending Payment'), ('Enrolled', 'Enrolled')], db_index=True, default='Pending Payment', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='sub_course',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course', 'session')},
        ),
    ]
