# Generated by Django 5.2.15 on 2026-07-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_student_course_student_lead_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='data_subject_consent',
            field=models.JSONField(blank=True, default=dict, help_text='DPDP Act 2023: {consent_given: bool, timestamp: ISO8601, scope: [...]}'),
        ),
    ]
