# Generated by Django 5.2.15 on 2026-07-13 21:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_add_dpdp_consent'),
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='abc_id',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='deb_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='employment_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='receipt_s3_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_leads', to='rules.intakesession'),
        ),
        migrations.AddField(
            model_name='studentacademichistory',
            name='examination',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentacademichistory',
            name='percentage_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentacademichistory',
            name='result',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='StudentAddress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('perm_domicile_type', models.CharField(max_length=50)),
                ('perm_address', models.TextField()),
                ('perm_country', models.CharField(max_length=100)),
                ('perm_state', models.CharField(max_length=100)),
                ('perm_district', models.CharField(max_length=100)),
                ('perm_city', models.CharField(max_length=100)),
                ('perm_pincode', models.CharField(max_length=6)),
                ('corr_address', models.TextField()),
                ('corr_country', models.CharField(max_length=100)),
                ('corr_state', models.CharField(max_length=100)),
                ('corr_district', models.CharField(max_length=100)),
                ('corr_city', models.CharField(max_length=100)),
                ('corr_pincode', models.CharField(max_length=6)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_block', to='admissions.student')),
            ],
            options={
                'db_table': 'student_addresses',
            },
        ),
    ]
