# Generated by Django 5.2.15 on 2026-07-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_student_abc_id_student_category_student_deb_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_semester',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='alternate_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='studentaddress',
            name='domicile_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentacademichistory',
            name='score_value',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
