# Generated by Django 5.2.15 on 2026-07-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_student_admission_semester_student_admission_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='aadhar_hash',
            field=models.CharField(db_index=True, help_text='SHA-256 hash of salted Aadhar number', max_length=64),
        ),
    ]
