# Generated by Django 5.2.16 on 2026-07-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0006_alter_student_aadhar_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdoc",
            name="doc_category",
            field=models.CharField(
                choices=[
                    ("identity", "Identity Proof"),
                    ("marklist", "Marklist / Certificate"),
                    ("migration", "Migration Certificate"),
                    ("experience", "Experience Certificate"),
                    ("photo", "Passport Photo"),
                    ("abc_id", "ABC ID"),
                    ("deb_id", "DEB ID"),
                    ("other", "Other"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
