# Generated by Django 5.2.16 on 2026-07-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0007_alter_studentdoc_doc_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="admission_number",
            field=models.CharField(
                blank=True,
                help_text="Assigned when status transitions to Enrolled",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="admission_type",
            field=models.CharField(
                blank=True,
                choices=[("fresh", "Fresh"), ("lateral", "Lateral")],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="registration_number",
            field=models.CharField(
                blank=True,
                help_text="Assigned when status transitions to Enrollment Generated",
                max_length=100,
            ),
        ),
    ]
