# Generated by Django 5.2.16 on 2026-07-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_add_enrollment_admission_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='aadhar_hash',
            field=models.CharField(help_text='SHA-256 hash of salted Aadhar number', max_length=64, unique=True),
        ),
    ]
