# Generated by Django 6.0.6 on 2026-07-01 17:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_fresh_allowed', models.BooleanField(default=True, help_text='Whether fresh candidates (no prior enrollment) can enroll in this session')),
            ],
            options={
                'db_table': 'intake_sessions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='RulesConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('conditions', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower = higher priority')),
            ],
            options={
                'db_table': 'rules_configurations',
                'ordering': ['priority', 'rule_name'],
            },
        ),
    ]
