# Generated by Django 6.0.6 on 2026-07-01 17:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=300, unique=True)),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('accreditation', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('logo_uri', models.URLField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'universities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('stream', models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate'), ('Diploma', 'Diploma'), ('Open Schooling', 'Open Schooling')], db_index=True, max_length=50)),
                ('duration_months', models.PositiveIntegerField()),
                ('eligibility_text', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='aggregator.university')),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UniversityDocVault',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('prospectus', 'Prospectus'), ('calendar', 'Academic Calendar'), ('syllabus', 'Syllabus'), ('notification', 'Official Notification')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('s3_object_uri', models.TextField()),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='aggregator.university')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_university_docs', to='partners.systemuser')),
            ],
            options={
                'db_table': 'university_doc_vault',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fee_type', models.CharField(choices=[('admission', 'Admission Fee'), ('tuition', 'Tuition Fee'), ('exam', 'Examination Fee'), ('library', 'Library Fee'), ('lab', 'Lab Fee'), ('other', 'Other')], db_index=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='aggregator.course')),
            ],
            options={
                'db_table': 'fee_structures',
                'ordering': ['fee_type'],
                'unique_together': {('course', 'fee_type', 'is_active')},
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['university', 'is_active'], name='courses_univers_f76933_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['stream', 'is_active'], name='courses_stream_01adb0_idx'),
        ),
        migrations.AddIndex(
            model_name='universitydocvault',
            index=models.Index(fields=['university', 'doc_type'], name='university__univers_664261_idx'),
        ),
        migrations.AddIndex(
            model_name='universitydocvault',
            index=models.Index(fields=['is_public'], name='university__is_publ_38669e_idx'),
        ),
    ]
