# Generated by Django 5.2.15 on 2026-07-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='eligibility_criteria_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
