# Generated by Django 5.2.15 on 2026-07-02 00:24

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0002_course_eligibility_criteria_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='course',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='courses_search__875182_gin'),
        ),
    ]
