# Generated by Django 5.2.15 on 2026-07-13 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0005_universitydocvault_course'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='universitydocvault',
            new_name='university__course__3100d4_idx',
            old_name='university_d_course_i_0d9f50_idx',
        ),
    ]
