# Generated by Django 5.2.16 on 2026-07-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "aggregator",
            "0006_rename_university_d_course_i_0d9f50_idx_university__course__3100d4_idx",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="feestructure",
            name="fee_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admission", "Admission Fee"),
                    ("tuition", "Tuition Fee"),
                    ("exam", "Examination Fee"),
                    ("library", "Library Fee"),
                    ("lab", "Lab Fee"),
                    ("other", "Other"),
                    ("", "Unspecified"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
