# Generated by Django 5.2.16 on 2026-07-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0007_alter_feestructure_fee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='fee_type',
            field=models.CharField(blank=True, choices=[('admission', 'Admission Fee'), ('tuition', 'Tuition Fee'), ('course_fee', 'Course Fee'), ('registration_fee', 'Registration Fee'), ('exam', 'Examination Fee'), ('library', 'Library Fee'), ('lab', 'Lab Fee'), ('other', 'Other'), ('', 'Unspecified')], db_index=True, max_length=30),
        ),
    ]
