# Generated by Django 5.2.16 on 2026-07-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0007_alter_feestructure_fee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='stream',
            field=models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate'), ('Diploma', 'Diploma'), ('Open Schooling', 'Open Schooling'), ('PG Diploma', 'PG Diploma'), ('Certification', 'Certification')], db_index=True, max_length=50),
        ),
    ]
