# Generated by Django 5.2.16 on 2026-07-24 06:31

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0007_alter_feestructure_fee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.AddConstraint(
            model_name='university',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), django.db.models.functions.text.Lower('state'), name='unique_university_name_state'),
        ),
    ]
