# Generated by Django 5.2.16 on 2026-07-30 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0008_alter_course_stream'),
        ('aggregator', '0008_alter_feestructure_fee_type'),
        ('aggregator', '0008_alter_university_name_and_more'),
    ]

    operations = [
    ]
