# Generated by Django 5.2.15 on 2026-07-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_subcenter_university_mapping'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='subcenteruniversitymapping',
            new_name='sub_center__sub_cen_e122f0_idx',
            old_name='sub_center__sub_cen_68c6ab_idx',
        ),
        migrations.RenameIndex(
            model_name='subcenteruniversitymapping',
            new_name='sub_center__univers_631fc5_idx',
            old_name='sub_center__universi_5a6a27_idx',
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin (MD)'), ('academic_head', 'Academic Head / Manager'), ('counselor', 'Counselor / Admission Officer'), ('finance', 'Finance / Accounts Officer'), ('subcenter', 'Sub-Center Admin')], db_index=True, max_length=30),
        ),
    ]
